FROM node:18-alpine

COPY --from=golang:1.17-alpine /usr/local/go/ /usr/local/go/

ENV VERCEL_TOKEN="__YOUR__TOKEN__"
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"
ENV GO_HOME="/usr/local/go/bin"
ENV PATH="${GO_HOME}:${PATH}"

WORKDIR /app
COPY . /app
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm i -g vercel

EXPOSE 3000
CMD ["sh", "-c", "vercel dev --listen 3000 -t ${VERCEL_TOKEN} --yes"]